logging:
  level:
    org.example: DEBUG

spring:
  jpa:
    database: mysql
    hibernate:
      ddl-auto: create
  datasource:
    url: "jdbc:mysql://localhost:3307/hrm"
    username: "root"
    password: "root"
