logging:
  level:
    org.example: DEBUG

server:
  port: 8081

spring:
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    database: mysql
    hibernate:
      ddl-auto: create
  datasource:
    url: "jdbc:mysql://localhost:3306/hrm"
    username: "root"
    password: "root"

  devtools:
    restart:
      poll-interval: 2s
      quiet-period: 1s
